import './js/header.js';
import './js/about-me-sasha';
import './js/covers.js';
import './js/faq.js';
import './js/reviews.js';
import './js/projects.js';
import './js/about-me-lesia';
import './js/footer.js';
import './js/aos.js';
